### ISSUE TITLE
feature request - filterpageedit 'Target Version'

### ISSUE THREAD

**Issue by brokentilez** [mantisbt-plugins/filter-page-edit#1]
The plugin currently allows custom_fields to be edited on the filter page and works great.  Is it possible to add 'Target Version' ( a non-custom field ) to this plugin?  We have thousands of bugs and are using Target Version for the roadmap feature.  Changing one bug at a time is tedious.

I'm noob to mantis plugins and know enough PHP to be dangerous.  If you can point me in the right direction,  I can try to add myself.

Thank you for your time and any assistance you may be able to add.
- Bill

**Comment by atrol** [comment]
You don't have to use a plugin to change the target version of thousands issues.
There is a menu at the bottom of the "View Issues" page for bulk operations. The last entry of this list is "Update Target Version".
Use the check boxes left beside the issues list to select the issues you want to change or the check box "Select all" for all issues.

**Comment by brokentilez** [comment]
Thanks so much!  I didn't even realize.  Now it's time to tweak this plugin to see why it quit working in 1.2.11, was OK in 1.2.0 ( i back dated the config ).  Thank you for your time.

**Comment by rombert** [comment]
Closing then, please report bug if you find any on the [MantisBT bugtracker](http://www.mantisbt.org/bugs), the Plugin - FilterPageEdit project.
