### ISSUE TITLE
MantisBT 1.2.11 requires quotes around name for jQuery

### ISSUE THREAD

**Issue by brokentilez** [mantisbt-plugins/filter-page-edit#2]
I could not get filter-page-edit working in mantis 1.2.11, mantis 1.2.0 worked fine, same version of jQuery.  I discovered that the bugTable.find function was failing in /pages/filter-page-edit.php, line 44 .

I would patch this out, but not exactly sure how.

Old:

...
var FilterPageEdit = {
    installCustomFieldEdit : function(fieldId, fieldName, displayEditable) {
        var bugTable = jQuery("#buglist");

```
    var checkboxes = bugTable.find('input[type=checkbox][name=bug_arr[]]');
   if ( checkboxes.length == 0 ) {
```

...

checkboxes would never return.

New Fixed:
...
var FilterPageEdit = {
    installCustomFieldEdit : function(fieldId, fieldName, displayEditable) {
        var bugTable = jQuery("#buglist");

```
 // added quotes around bug_arr[]
    var checkboxes = bugTable.find('input[type=checkbox][name="bug_arr[]"]');
   if ( checkboxes.length == 0 ) {
```

...

checkboxes now return and plugin is working again.  

Thank you so much for your time in making this great plugin.

**Comment by rombert** [comment]
Thanks for the report, I'll try to reproduce the problem.

**Comment by rombert** [comment]
I've applied the fix , thanks for tracking this down. In the future, please report issues on www.mantisbt.org as noted in [the plugin wiki](http://www.mantisbt.org/wiki/doku.php/mantisbt:filterpageedit) since I keep track of them easier.
